config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  resources :funcionarios
  resources :imovels do
      resources :imovel_moradors
  end
  resources :moradors
  resources :sessions, only: %i[new create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/funcionario.rb
class Funcionario < ApplicationRecord
  validates :nome, :matricula, presence: true
end

app/models/imovel.rb
class Imovel < ApplicationRecord
    has_many :imovel_moradors, class_name: 'ImovelMorador'
end

app/models/imovel_morador.rb
class ImovelMorador < ApplicationRecord
  belongs_to :imovel, required: false
  belongs_to :morador, required: false

  attr_accessor :cpf

  validates :cpf, :processo, presence: true

  before_save :vincular_morador

  def vincular_morador
      @morador = Morador.find_by(cpf: self.cpf)

     if @morador.present?
       self.morador_id = @morador.id
     else
       errors.add(:cpf, "Cpf inexistente.")
     end

  end

end

app/models/morador.rb
class Morador < ApplicationRecord
  has_many :imovel_moradors, class_name: 'ImovelMorador'
end

app/models/session.rb
class Session
  include ActiveModel::Model
  attr_accessor :matricula, :password, :id

  validate :autenticar
  validates :password, :matricula, presence: true

  def autenticar
    @validar = Funcionario.where(matricula: self.matricula, senha: self.password).first
    if @validar.present?
      self.id = @validar.id
    else
     errors.add(:password, "Matrícula ou Senha não conferem.")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :validar_session

  def validar_session
    unless session[:usuario_id].present?
      redirect_to new_session_path
    end
  end
end

app/controllers/funcionarios_controller.rb
require_dependency 'application_controller'

class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: %i[edit update destroy show]

  def index
    @funcionarios = ::Funcionario.all
  end

  def new
    @funcionario = Funcionario.new
  end

  def create
    @funcionario = Funcionario.new(set_params)
    if @funcionario.save
      redirect_to funcionarios_path
    else
      render action: :new
    end
  end

  def edit
  end

  def update
    if @funcionario.update(set_params)
    redirect_to funcionarios_path
    else
      render action: :edit
    end
  end

  def destroy
    if @funcionario.destroy
      redirect_to funcionarios_path
    else
      render action: :edit
    end
  end

  def show
  end

  private

  def set_params
    params.require(:funcionario).permit(:nome, :matricula, :cargo, :senha)
  end

  def set_funcionario
    @funcionario = Funcionario.find(params[:id])
  end
end

app/controllers/imovel_moradors_controller.rb
require_dependency 'application_controller'

class ImovelMoradorsController < ApplicationController
  before_action :set_imovel
  before_action :set_morador, only: %i[edit update destroy show]

  def index
    @imovel_morador = @imovel.imovel_moradors.all
  end

  def new
    @imovel_morador = @imovel.imovel_moradors.new
  end

  def create
    @imovel_morador = @imovel.imovel_moradors.new(set_params)
    @imovel_morador.funcionario_id = session[:usuario_id]

    if @imovel_morador.save
      redirect_to moradors_path
    else
      render action: :new
    end
  end

  def destroy
    if @imovel_morador.destroy
      redirect_to moradors_path
    end
  end

  def show
    render layout: 'layouts/document'
  end

  private

  def set_params
    params.require(:imovel_morador).permit(:cpf, :processo)
  end

  def set_imovel
    @imovel = Imovel.find(params[:imovel_id])
  end

  def set_morador
    @imovel_morador = ImovelMorador.find(params[:id])
  end
end

app/controllers/imovels_controller.rb
require_dependency 'application_controller'

class ImovelsController < ApplicationController
  before_action :set_imovel, only: %i[edit update destroy show]

  def index
    @imovels = Imovel.all
  end

  def new
    @imovel = Imovel.new
  end

  def create
    @imovel = Imovel.new(set_params)
    if @imovel.save
      redirect_to imovels_path
    else
      render action: :new
    end
  end

  def edit
  end

  def update
    if @imovel.update(set_params)
    redirect_to imovels_path
    else
      render action: :edit
    end
  end

  def destroy
    if @imovel.destroy
      redirect_to imovels_path
    else
      render action: :edit
    end
  end

  def show
  end

  private

  def set_params
    params.require(:imovel).permit(:endereco, :iptu, :area, :matricula, :cidade, :ato_declaratorio)
  end

  def set_imovel
    @imovel = Imovel.find(params[:id])
  end
end

app/controllers/moradors_controller.rb
require_dependency 'application_controller'

class MoradorsController < ApplicationController
  before_action :set_morador, only: %i[edit update destroy show]

  def index
    @moradors = ::Morador.all
  end

  def new
    @morador = Morador.new
  end

  def create
    @morador = Morador.new(set_params)
    if @morador.save
      redirect_to moradors_path
    else
      render action: :new
    end
  end

  def edit
  end

  def update
    if @morador.update(set_params)
    redirect_to moradors_path
    else
      render action: :edit
    end
  end

  def destroy
    if @morador.destroy
      redirect_to moradors_path
    end
  end

  def show
  end

  private

  def set_params
    params.require(:morador).permit(:nome, :cpf, :rg, :est_civil, :profissao, :nome_conjuge, :cpf_conjuge, :profissao_conjuge, :est_civil_conjuge)
  end

  def set_morador
    @morador = Morador.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ActionController::Base
  layout 'login'
  def new
    @autenticar = Session.new
  end

  def create
    @autenticar = Session.new(set_params)
    if @autenticar.valid?
      session[:usuario_id] = @autenticar.id
      redirect_to funcionarios_path
    else
      render action: :new
    end
  end

  private

  def set_params
    params.require(:session).permit(:matricula, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/funcionarios/_form.html.erb
<%= simple_form_for @funcionario do |f| %>


  <div class="row">

      <div class='col-md-6'>
        <%= f.input :nome, label: 'Digite seu nome', input_html:{ class: "form-control"} %>
      </div>
      <div class='col-md-6'>
       <%= f.input :matricula, label: 'Digite sua matricula', input_html:{ class: "form-control"} %>
      </div>
      <div class='col-md-6'>
       <%= f.input :cargo, label: 'Digite seu cargo', input_html:{ class: "form-control"} %>
      </div>
      <div class='col-md-6'>
       <%= f.input :senha, label: 'Digite sua senha', input_html:{ class: "form-control"} %>
      </div>
  </div>

  <div class="row">
    <div class='col-md-12'>
      <br>
     <%= f.button :submit, class: 'btn btn-success' %>
   </div>
 </div>


<% end -%>

app/views/funcionarios/edit.html.erb
<div>
  <h3>
    Editar Funcionario
  </h3>
</div>

<div>
  <%= render 'form' %>

</div>

app/views/funcionarios/index.html.erb
<div>
    <%= link_to 'Novo Funcionario', new_funcionario_path, class:'btn btn-primary' %>
</div>
<div>
  <br>
  Lista de Funcionarios
  <br>
  <br>
</div>
<div>

  <table class="table">

      <thead>
        <tr>
          <td>
            Nome
          </td>
          <td>
            Matricula
          </td>
          <td>
            Cargo
          </td>
          <td></td>
          <td></td>
        </tr>

      </thead>

      <tbody>

        <% @funcionarios.each do |funcionario| %>


        <tr>
            <td>

              <%= funcionario.nome%>

            </td>
            <td>

              <%= funcionario.matricula%>

            </td>
            <td>

              <%= funcionario.cargo%>

            </td>

            <td>

              <%= link_to 'Editar', edit_funcionario_path(funcionario), class:'btn btn-warning' %>

            </td>
            <td>

              <%= link_to 'Excluir', funcionario, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %>

            </td>
        </tr>

        <% end %>

      </tbody>


  </table>

</div>

app/views/funcionarios/new.html.erb
<div>
  <h3>
    Novo Funcionario
  </h3>
</div>

<div>
  <%= render 'form' %>

</div>

app/views/imovel_moradors/_form.html.erb
<%= simple_form_for [@imovel,@imovel_morador] do |f| %>


  <div class="row">

        <div class='col-md-6'>
          <%= f.input :cpf, label: 'CPF', input_html:{ class: "form-control"} %>
        </div>
        <div class='col-md-6'>
         <%= f.input :processo, label: 'Processo', input_html:{ class: "form-control"} %>
        </div>

  </div>

  <div class="row">
    <div class='col-md-12'>
      <br>
     <%= f.button :submit, class: 'btn btn-success' %>
   </div>
 </div>


<% end -%>

app/views/imovel_moradors/new.html.erb
<div>
  <h3>
  <%= "Vincular Morador ao endereço: #{@imovel.endereco}" %>
  </h3>
</div>

<div>
  <%= render 'form' %>

</div>

app/views/imovels/_form.html.erb
<%= simple_form_for @imovel do |f| %>


  <div class="row">

    <tr>
        <div class='col-md-6'>
          <%= f.input :endereco, label: 'Endereço', input_html:{ class: "form-control"} %>
        </div>
        <div class='col-md-6'>
         <%= f.input :iptu, label: 'Iptu', input_html:{ class: "form-control"} %>
        </div>
        <div class='col-md-6'>
         <%= f.input :area, label: 'Area', input_html:{ class: "form-control"} %>
        </div>
        <div class='col-md-6'>
         <%= f.input :matricula, label: 'Matricula', input_html:{ class: "form-control"} %>
        </div>
        <div class='col-md-6'>
         <%= f.input :cidade, label: 'Cidade', input_html:{ class: "form-control"} %>
        </div>
        <div class='col-md-6'>
         <%= f.input :ato_declaratorio, label: 'Ato Declaratorio', input_html:{ class: "form-control"} %>
        </div>
    </tr>
  </div>

  <div class="row">
    <div class='col-md-12'>
      <br>
     <%= f.button :submit, "Salvar", class: 'btn btn-success' %>
   </div>
 </div>


<% end -%>

app/views/imovels/edit.html.erb
<div>
  <h3>
    Editar Imóvel
  </h3>
</div>

<div>
  <%= render 'form' %>

</div>

app/views/imovels/index.html.erb
    <div class="row">
      <div class="col-md-12">
        <%= link_to 'Novo Imóvel', new_imovel_path, class:'btn btn-primary' %>
      </div>
    </div>
    <br />
    <br />
    <div class="row">
      <div class="col-md-12">
        <table class="table table-hover">
          <thead>
            <tr>
              <td>
                Cidade
              </td>
              <td>
                Endereco
              </td>
              <td>
                Morador
              </td>
              <td></td>

            </tr>
          </thead>
          <tbody>
                <% @imovels.each do |imovel| %>
                   <td scope="col">
                     <%= imovel.cidade%>
                   </td>
                    <td scope="col">
                      <%= imovel.endereco%>
                    </td>
                    <td scope="col">
                      <%= imovel.imovel_moradors.last.morador.nome rescue "Imovel vago" %>
                    </td>
                    <td scope="col">
                      <div class="btn-group" role="group">
                          <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Opções
                          </button>
                          <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                            <%= link_to 'Escritura', imovel_imovel_morador_path(imovel, imovel.imovel_moradors.last.id), class:'dropdown-item' if imovel.imovel_moradors.present? %>
                            <%= link_to 'Visualizar', imovel_path(imovel), class:'dropdown-item' %>
                            <%= link_to 'Editar', edit_imovel_path(imovel), class:'dropdown-item' %>
                            <%= link_to 'Excluir', imovel_path(imovel), method: :delete, data: { confirm: 'Are you sure?' }, class:'dropdown-item' %>
                            <%= link_to 'Assentar', new_imovel_imovel_morador_path(imovel), class:'dropdown-item' %>
                          </div>
                        </div>

                    </td>
                </tr>

                <% end %>

              </tbody>


          </table>
      </div>
    </div>

app/views/imovels/new.html.erb
<div>
  <h3>
    Novo Imovel
  </h3>
</div>

<div>
  <%= render 'form' %>

</div>

app/views/imovels/show.html.erb
<div>
<%= link_to 'Voltar', imovels_path, class:'btn btn-dark' %>
</div>
<br>
<br>
<div>
  <table class="table">
          <thead>
              <tr>
                  <td>
                    Endereco
                  </td>
                  <td>
                    Iptu
                  </td>
                  <td>
                    Area
                  </td>
                  <td>
                    Matricula
                  </td>
                  <td>
                    Cidade
                  </td>
                  <td>
                    Ato Declaratorio
                  </td>
                  <td>
                    Morador Vinculado
                  </td>
              </tr>
          </thead>
    <tbody>
            <td>
              <%= @imovel.endereco%>
            </td>
            <td>
              <%= @imovel.iptu%>
            </td>
            <td>
              <%= @imovel.area%>
            </td>
            <td>
              <%= @imovel.matricula%>
            </td>
            <td>
              <%= @imovel.cidade%>
            </td>
            <td>
              <%= @imovel.ato_declaratorio%>
            </td>
            <td>
              <%= @imovel.imovel_moradors.last.morador.nome rescue "Imóvel vago"%>
            </td>

        </tr>

      </tbody>


  </table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cartorio</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">
          <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQstD4Eh7ReEXin0mCJa159D9htE5alMoiaNWvD6DimRU0Qcy0qQA" width="200" height="40" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/funcionarios">Funcionarios</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/moradors">Moradores</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/imovels">Imoveis</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <br>
      <br>
      <br>
      <br>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/document.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cartorio</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'document', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cartorio</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="container">
    	<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="panel panel-login">
					<div class="panel-heading">
						<div class="row">
						</div>
						<hr>
					</div>
					<div class="panel-body">
            <%= yield %>
					</div>
				</div>
			</div>
		</div>
	</div>
  </body>
</html>

app/views/moradors/_form.html.erb
<%= simple_form_for @morador do |f| %>


  <div class="row">

      <div class='col-md-12'>
        <h4>Titular </h4>
      </div>

      <div class='col-md-6'>
        <%= f.input :nome, label: 'Nome: ', input_html:{ class: "form-control"} %>
      </div>
      <div class='col-md-6'>
       <%= f.input :cpf, label: 'Cpf: ', input_html:{ class: "form-control"} %>
      </div>
      <div class='col-md-6'>
       <%= f.input :rg, label: 'RG: ', input_html:{ class: "form-control"} %>
      </div>
      <div class='col-md-6'>
       <%= f.input :est_civil, label: 'Estado Civil: ', input_html:{ class: "form-control"} %>
      </div>
      <div class='col-md-6'>
       <%= f.input :profissao, label: 'Profissao: ', input_html:{ class: "form-control"} %>
      </div>

      <div class='col-md-12'>
        <h4> Conjuge </h4>
      </div>

      <div class='col-md-6'>

        <%= f.input :nome_conjuge, label: 'Nome: ', input_html:{ class: "form-control"} %>
      </div>
      <div class='col-md-6'>
        <%= f.input :cpf_conjuge, label: 'Cpf: ', input_html:{ class: "form-control"} %>
      </div>
      <div class='col-md-6'>
        <%= f.input :profissao_conjuge, label: 'Profissao: ', input_html:{ class: "form-control"} %>
      </div>
      <div class='col-md-6'>
        <%= f.input :est_civil_conjuge, label: 'Estado Cilvil: ', input_html:{ class: "form-control"} %>
      </div>

  </div>

  <div class="row">
    <div class='col-md-12'>
      <br>
     <%= f.button :submit, class: 'btn btn-success' %>
   </div>
 </div>


<% end -%>

app/views/moradors/edit.html.erb
<div>
  <h3>
    Editar Morador
  </h3>
</div>

<div>
  <%= render 'form' %>

</div>

app/views/moradors/index.html.erb
<div>
    <%= link_to 'Novo Morador', new_morador_path, class:'btn btn-primary' %>
</div>

<div>

  <table class="table">

        <thead>
              <br>
              <br>
              Lista de Moradores
              <br>
              <br>
              <tr>
                <td>
                  <div class='col-md-4'>
                  Nome
                 </div>
                </td>

                <td>
                  <div class='col-md-4'>
                    Cpf
                  </div>
                </td>

        </thead>
      <tbody>

        <% @moradors.each do |morador| %>

        <tr>
            <td class="col-md-4">
              <%= morador.nome%>
            </td>
            <td class="col-md-2">
              <%= morador.cpf%>
            </td>

            <td class="col-md-2">
              <%= link_to 'Visualizar', morador_path(morador), class:'btn btn-info btn-sm' %>
            </td>
            <td class="col-md-2">
              <%= link_to 'Editar', edit_morador_path(morador), class:'btn btn-warning' %>
            </td>
            <td class="col-md-2">
              <%= link_to 'Excluir', morador_path(morador), method: :delete, data: {  confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            </td>
        </tr>

        <% end %>

      </tbody>


  </table>

</div>

app/views/moradors/new.html.erb
<div>
  <h2>
    Novo Morador
  </h2>
</div>

<div>
  <%= render 'form' %>

</div>

app/views/moradors/show.html.erb
<div>

  <table class="table">

        <thead>

              Lista de Moradores
              <tr>
                <td>
                  <div class='col-md-2'>
                  Nome
                 </div>
                </td>

                <td>
                  <div class='col-md-2'>
                    Cpf
                  </div>
                </td>

                <td>
                  <div class='col-md-2'>
                  Rg
                  </div>
                </td>
                <td>
                  <div class='col-md-2'>
                  Estado Civil
                  </div>
                </td>
                <td>
                  <div class='col-md-2'>
                  Profissao
                  </div>
                </td>
                <td>
                  <div class='col-md-2'>
                  Nome Conjuge
                  </div>
                </td>
                <td>
                  <div class='col-md-2'>
                  Cpf Conjuge
                  </div>
                </td>
                <td>
                  <div class='col-md-2'>
                  Profissao Conjuge
                  </div>
                </td>
                <td>
                  <div class='col-md-2'>
                  Estado Civil Conjuge
                  </div>
                </td>
              </tr>
        </thead>
      <tbody>


        <tr>
            <td>

              <%= @morador.nome%>
            </td>
            <td>
              <%= @morador.cpf%>
            </td>
            <td>
              <%= @morador.rg%>
            </td>
            <td>
              <%= @morador.est_civil%>
            </td>
            <td>
              <%= @morador.profissao%>
            </td>
            <td>
              <%= @morador.nome_conjuge%>
            </td>
            <td>
              <%= @morador.cpf_conjuge%>
            </td>
            <td>
              <%= @morador.profissao_conjuge%>
            </td>
            <td>
              <%= @morador.est_civil_conjuge%>
            </td>
        </tr>


      </tbody>


  </table>

</div>